// <auto-generated />
using System;
using CryptoTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoTracker.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("CryptoTracker.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CryptocurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAlert")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrency");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CryptoAmout")
                        .HasColumnType("REAL");

                    b.Property<int?>("CryptocurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("CryptoTracker.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CryptocurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Alert", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Cryptocurrency", "Cryptocurrency")
                        .WithMany("Alerts")
                        .HasForeignKey("CryptocurrencyId");

                    b.HasOne("CryptoTracker.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId");

                    b.Navigation("Cryptocurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Transaction", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Cryptocurrency", "Cryptocurrency")
                        .WithOne("Transaction")
                        .HasForeignKey("CryptoTracker.Entities.Transaction", "CryptocurrencyId");

                    b.HasOne("CryptoTracker.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("CryptoTracker.Entities.Wallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId");

                    b.Navigation("Cryptocurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Wallet", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Cryptocurrency", null)
                        .WithMany("Wallets")
                        .HasForeignKey("CryptocurrencyId");

                    b.HasOne("CryptoTracker.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("CryptoTracker.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Cryptocurrency", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Transaction");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("CryptoTracker.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
