// <auto-generated />
using System;
using CryptoTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoTracker.DataAccess.Migrations
{
    [DbContext(typeof(CryptoStorageContext))]
    [Migration("20210316193819_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CryptocurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAlert")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrencies");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CryptoAmout")
                        .HasColumnType("float");

                    b.Property<int?>("CryptocurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId")
                        .IsUnique()
                        .HasFilter("[CryptocurrencyId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nick")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptocurrencyWallet", b =>
                {
                    b.Property<int>("CryptocurrenciesId")
                        .HasColumnType("int");

                    b.Property<int>("WalletsId")
                        .HasColumnType("int");

                    b.HasKey("CryptocurrenciesId", "WalletsId");

                    b.HasIndex("WalletsId");

                    b.ToTable("CryptocurrencyWallet");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Alert", b =>
                {
                    b.HasOne("CryptoTracker.DataAccess.Entities.Cryptocurrency", "Cryptocurrency")
                        .WithMany("Alerts")
                        .HasForeignKey("CryptocurrencyId");

                    b.HasOne("CryptoTracker.DataAccess.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId");

                    b.Navigation("Cryptocurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Transaction", b =>
                {
                    b.HasOne("CryptoTracker.DataAccess.Entities.Cryptocurrency", "Cryptocurrency")
                        .WithOne("Transaction")
                        .HasForeignKey("CryptoTracker.DataAccess.Entities.Transaction", "CryptocurrencyId");

                    b.HasOne("CryptoTracker.DataAccess.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Cryptocurrency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Wallet", b =>
                {
                    b.HasOne("CryptoTracker.DataAccess.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("CryptoTracker.DataAccess.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryptocurrencyWallet", b =>
                {
                    b.HasOne("CryptoTracker.DataAccess.Entities.Cryptocurrency", null)
                        .WithMany()
                        .HasForeignKey("CryptocurrenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoTracker.DataAccess.Entities.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.Cryptocurrency", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CryptoTracker.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Transactions");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
